// This code is generated by TableGenerator.exe
//
// Fixed point format: 8.24
// Units: 6.283185 (6.28 is radians, 360 is degrees)

int const	NUMBER_OF_ITERATIONS	= 25;
Cordic::Fixed const	angles[ NUMBER_OF_ITERATIONS ] =
{
	CordicCalculator::Fixed( 0,  13176795 ),	// atan( pow( 2, -0  ) )
	CordicCalculator::Fixed( 0,   7778716 ),	// atan( pow( 2, -1  ) )
	CordicCalculator::Fixed( 0,   4110060 ),	// atan( pow( 2, -2  ) )
	CordicCalculator::Fixed( 0,   2086331 ),	// atan( pow( 2, -3  ) )
	CordicCalculator::Fixed( 0,   1047214 ),	// atan( pow( 2, -4  ) )
	CordicCalculator::Fixed( 0,    524117 ),	// atan( pow( 2, -5  ) )
	CordicCalculator::Fixed( 0,    262123 ),	// atan( pow( 2, -6  ) )
	CordicCalculator::Fixed( 0,    131069 ),	// atan( pow( 2, -7  ) )
	CordicCalculator::Fixed( 0,     65536 ),	// atan( pow( 2, -8  ) )
	CordicCalculator::Fixed( 0,     32768 ),	// atan( pow( 2, -9  ) )
	CordicCalculator::Fixed( 0,     16384 ),	// atan( pow( 2, -10 ) )
	CordicCalculator::Fixed( 0,      8192 ),	// atan( pow( 2, -11 ) )
	CordicCalculator::Fixed( 0,      4096 ),	// atan( pow( 2, -12 ) )
	CordicCalculator::Fixed( 0,      2048 ),	// atan( pow( 2, -13 ) )
	CordicCalculator::Fixed( 0,      1024 ),	// atan( pow( 2, -14 ) )
	CordicCalculator::Fixed( 0,       512 ),	// atan( pow( 2, -15 ) )
	CordicCalculator::Fixed( 0,       256 ),	// atan( pow( 2, -16 ) )
	CordicCalculator::Fixed( 0,       128 ),	// atan( pow( 2, -17 ) )
	CordicCalculator::Fixed( 0,        64 ),	// atan( pow( 2, -18 ) )
	CordicCalculator::Fixed( 0,        32 ),	// atan( pow( 2, -19 ) )
	CordicCalculator::Fixed( 0,        16 ),	// atan( pow( 2, -20 ) )
	CordicCalculator::Fixed( 0,         8 ),	// atan( pow( 2, -21 ) )
	CordicCalculator::Fixed( 0,         4 ),	// atan( pow( 2, -22 ) )
	CordicCalculator::Fixed( 0,         2 ),	// atan( pow( 2, -23 ) )
	CordicCalculator::Fixed( 0,         1 ),	// atan( pow( 2, -24 ) )
};

static Cordic::Fixed const	C( 0, 10188014 );	// 0.607253 
